-- 039_expanded_word_rules.sql
-- Builds on 038: adds a "support" action + "self_harm" category, then seeds a
-- much larger starter list (327 rules). Safe to re-run (existing terms are skipped).
--
-- What each action does:
--   block   = post is rejected (attempt is logged to Flagged content)
--   flag    = post publishes, lands in Flagged content for review
--   support = post publishes, author is shown help resources, NOT queued as a violation
--
-- Hard slurs, credential-theft requests, incitement and sexual-violence threats
-- are set to BLOCK. Everything with common innocent uses is FLAG so you can watch
-- for false positives first. Review and adjust in Admin -> Trust & safety -> Word rules.

DO $$
DECLARE c record;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
     WHERE conrelid = 'content_rules'::regclass AND contype = 'c'
       AND (pg_get_constraintdef(oid) LIKE '%action%' OR pg_get_constraintdef(oid) LIKE '%category%')
  LOOP
    EXECUTE format('ALTER TABLE content_rules DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

ALTER TABLE content_rules ADD CONSTRAINT content_rules_action_check
  CHECK (action IN ('flag', 'block', 'support'));
ALTER TABLE content_rules ADD CONSTRAINT content_rules_category_check
  CHECK (category IN ('abuse', 'hate', 'threat', 'scam', 'spam', 'sexual', 'self_harm', 'other'));

INSERT INTO content_rules (term, match_type, action, category) VALUES
  ('send your otp', 'word', 'block', 'scam'),
  ('send ur otp', 'word', 'block', 'scam'),
  ('send me ur otp', 'word', 'block', 'scam'),
  ('give me your otp', 'word', 'block', 'scam'),
  ('give me ur otp', 'word', 'block', 'scam'),
  ('share your otp', 'word', 'block', 'scam'),
  ('share ur otp', 'word', 'block', 'scam'),
  ('share your otp with me', 'word', 'block', 'scam'),
  ('drop your otp', 'word', 'block', 'scam'),
  ('drop ur otp', 'word', 'block', 'scam'),
  ('tell me your otp', 'word', 'block', 'scam'),
  ('forward your otp', 'word', 'block', 'scam'),
  ('send me the otp', 'word', 'block', 'scam'),
  ('send me the code you received', 'word', 'block', 'scam'),
  ('send me the code sent to you', 'word', 'block', 'scam'),
  ('send me the verification code', 'word', 'block', 'scam'),
  ('send me your verification code', 'word', 'block', 'scam'),
  ('send your verification code', 'word', 'block', 'scam'),
  ('send me the 6 digit code', 'word', 'block', 'scam'),
  ('send me your 6 digit code', 'word', 'block', 'scam'),
  ('send your pin', 'word', 'block', 'scam'),
  ('send ur pin', 'word', 'block', 'scam'),
  ('send me ur pin', 'word', 'block', 'scam'),
  ('give me your pin', 'word', 'block', 'scam'),
  ('give me ur pin', 'word', 'block', 'scam'),
  ('drop your pin', 'word', 'block', 'scam'),
  ('drop ur pin', 'word', 'block', 'scam'),
  ('share your pin', 'word', 'block', 'scam'),
  ('tell me your pin', 'word', 'block', 'scam'),
  ('send me your atm pin', 'word', 'block', 'scam'),
  ('send me your card pin', 'word', 'block', 'scam'),
  ('send your bvn', 'word', 'block', 'scam'),
  ('send ur bvn', 'word', 'block', 'scam'),
  ('send me ur bvn', 'word', 'block', 'scam'),
  ('give me your bvn', 'word', 'block', 'scam'),
  ('drop your bvn', 'word', 'block', 'scam'),
  ('drop ur bvn', 'word', 'block', 'scam'),
  ('share your bvn', 'word', 'block', 'scam'),
  ('send your password', 'word', 'block', 'scam'),
  ('send ur password', 'word', 'block', 'scam'),
  ('send me ur password', 'word', 'block', 'scam'),
  ('give me your password', 'word', 'block', 'scam'),
  ('give me ur password', 'word', 'block', 'scam'),
  ('share your password', 'word', 'block', 'scam'),
  ('send me your card number', 'word', 'block', 'scam'),
  ('send me your cvv', 'word', 'block', 'scam'),
  ('send me your card details', 'word', 'block', 'scam'),
  ('send me your cvv number', 'word', 'block', 'scam'),
  ('give me your card number', 'word', 'block', 'scam'),
  ('give me your cvv', 'word', 'block', 'scam'),
  ('send your cvv', 'word', 'block', 'scam'),
  ('send me your seed phrase', 'word', 'block', 'scam'),
  ('send me your recovery phrase', 'word', 'block', 'scam'),
  ('send me your private key', 'word', 'block', 'scam'),
  ('share your seed phrase', 'word', 'block', 'scam'),
  ('verify your account by clicking', 'word', 'flag', 'scam'),
  ('click the link to verify', 'word', 'flag', 'scam'),
  ('your account will be suspended', 'word', 'flag', 'scam'),
  ('your account has been suspended click', 'word', 'flag', 'scam'),
  ('your account has been compromised', 'word', 'flag', 'scam'),
  ('spup support team', 'word', 'flag', 'scam'),
  ('spup customer care', 'word', 'flag', 'scam'),
  ('spup admin here', 'word', 'flag', 'scam'),
  ('i am from spup', 'word', 'flag', 'scam'),
  ('triple your money', 'word', 'flag', 'scam'),
  ('multiply your money', 'word', 'flag', 'scam'),
  ('flip your money', 'word', 'flag', 'scam'),
  ('money flip', 'word', 'flag', 'scam'),
  ('doubling your money', 'word', 'flag', 'scam'),
  ('guaranteed profit', 'word', 'flag', 'scam'),
  ('guaranteed profits', 'word', 'flag', 'scam'),
  ('100% guaranteed', 'word', 'flag', 'scam'),
  ('100 percent guaranteed', 'word', 'flag', 'scam'),
  ('100% profit', 'word', 'flag', 'scam'),
  ('risk free investment', 'word', 'flag', 'scam'),
  ('risk-free investment', 'word', 'flag', 'scam'),
  ('no risk investment', 'word', 'flag', 'scam'),
  ('get rich quick', 'word', 'flag', 'scam'),
  ('make money from home', 'word', 'flag', 'scam'),
  ('work from home and earn', 'word', 'flag', 'scam'),
  ('earn daily', 'word', 'flag', 'scam'),
  ('invest and earn', 'word', 'flag', 'scam'),
  ('send 5k get', 'word', 'flag', 'scam'),
  ('send 10k get', 'word', 'flag', 'scam'),
  ('send 20k get', 'word', 'flag', 'scam'),
  ('send 50k get', 'word', 'flag', 'scam'),
  ('send 100k get', 'word', 'flag', 'scam'),
  ('pay 5k get', 'word', 'flag', 'scam'),
  ('invest 10k get', 'word', 'flag', 'scam'),
  ('investment doubler', 'word', 'flag', 'scam'),
  ('crypto doubler', 'word', 'flag', 'scam'),
  ('crypto giveaway', 'word', 'flag', 'scam'),
  ('forex signals', 'word', 'flag', 'scam'),
  ('binary options', 'word', 'flag', 'scam'),
  ('cbn grant', 'word', 'flag', 'scam'),
  ('federal government grant', 'word', 'flag', 'scam'),
  ('free airtime', 'word', 'flag', 'scam'),
  ('free data giveaway', 'word', 'flag', 'scam'),
  ('claim your prize', 'word', 'flag', 'scam'),
  ('you have won', 'word', 'flag', 'scam'),
  ('congratulations you have won', 'word', 'flag', 'scam'),
  ('you are a winner', 'word', 'flag', 'scam'),
  ('click the link to claim', 'word', 'flag', 'scam'),
  ('click here to claim', 'word', 'flag', 'scam'),
  ('claim your reward', 'word', 'flag', 'scam'),
  ('loan without collateral', 'word', 'flag', 'scam'),
  ('instant loan', 'word', 'flag', 'scam'),
  ('quick loan', 'word', 'flag', 'scam'),
  ('get a loan in minutes', 'word', 'flag', 'scam'),
  ('blank atm card', 'word', 'flag', 'scam'),
  ('clone atm card', 'word', 'flag', 'scam'),
  ('cloned cards', 'word', 'flag', 'scam'),
  ('hacked paypal', 'word', 'flag', 'scam'),
  ('hire a hacker', 'word', 'flag', 'scam'),
  ('hack any account', 'word', 'flag', 'scam'),
  ('recover your lost funds', 'word', 'flag', 'scam'),
  ('recover lost funds', 'word', 'flag', 'scam'),
  ('follow for follow', 'word', 'flag', 'spam'),
  ('follow me and i follow back', 'word', 'flag', 'spam'),
  ('follow me i follow back', 'word', 'flag', 'spam'),
  ('follow back instantly', 'word', 'flag', 'spam'),
  ('f4f', 'word', 'flag', 'spam'),
  ('l4l', 'word', 'flag', 'spam'),
  ('like for like', 'word', 'flag', 'spam'),
  ('sub4sub', 'word', 'flag', 'spam'),
  ('sub for sub', 'word', 'flag', 'spam'),
  ('gain followers fast', 'word', 'flag', 'spam'),
  ('get free followers', 'word', 'flag', 'spam'),
  ('buy followers', 'word', 'flag', 'spam'),
  ('buy instagram followers', 'word', 'flag', 'spam'),
  ('sell followers', 'word', 'flag', 'spam'),
  ('followers for sale', 'word', 'flag', 'spam'),
  ('get 1000 followers', 'word', 'flag', 'spam'),
  ('dm me to earn', 'word', 'flag', 'spam'),
  ('dm to earn', 'word', 'flag', 'spam'),
  ('message me to earn', 'word', 'flag', 'spam'),
  ('whatsapp me to earn', 'word', 'flag', 'spam'),
  ('join my telegram', 'word', 'flag', 'spam'),
  ('join my telegram channel', 'word', 'flag', 'spam'),
  ('join our telegram', 'word', 'flag', 'spam'),
  ('join my whatsapp group', 'word', 'flag', 'spam'),
  ('join our whatsapp group', 'word', 'flag', 'spam'),
  ('whatsapp me on', 'word', 'flag', 'spam'),
  ('chat me on whatsapp', 'word', 'flag', 'spam'),
  ('chat me on telegram', 'word', 'flag', 'spam'),
  ('dm me on telegram', 'word', 'flag', 'spam'),
  ('text me on whatsapp', 'word', 'flag', 'spam'),
  ('contact me on whatsapp', 'word', 'flag', 'spam'),
  ('click the link in my bio', 'word', 'flag', 'spam'),
  ('earn money online', 'word', 'flag', 'spam'),
  ('make money online', 'word', 'flag', 'spam'),
  ('online jobs available', 'word', 'flag', 'spam'),
  ('part time job available', 'word', 'flag', 'spam'),
  ('i know where you live', 'word', 'flag', 'threat'),
  ('i will find you', 'word', 'flag', 'threat'),
  ('i go find you', 'word', 'flag', 'threat'),
  ('i will hunt you', 'word', 'flag', 'threat'),
  ('i will stab you', 'word', 'flag', 'threat'),
  ('i go stab you', 'word', 'flag', 'threat'),
  ('i will shoot you', 'word', 'flag', 'threat'),
  ('i go shoot you', 'word', 'flag', 'threat'),
  ('i will beat you up', 'word', 'flag', 'threat'),
  ('i will burn your house', 'word', 'flag', 'threat'),
  ('burn your house', 'word', 'flag', 'threat'),
  ('i go deal with you', 'word', 'flag', 'threat'),
  ('you dey die', 'word', 'flag', 'threat'),
  ('you will die', 'word', 'flag', 'threat'),
  ('i will hurt you', 'word', 'flag', 'threat'),
  ('i go hurt you', 'word', 'flag', 'threat'),
  ('i will murder you', 'word', 'flag', 'threat'),
  ('i go murder you', 'word', 'flag', 'threat'),
  ('death threat', 'word', 'flag', 'threat'),
  ('you are a dead man', 'word', 'flag', 'threat'),
  ('i will rape you', 'word', 'block', 'threat'),
  ('i go rape you', 'word', 'block', 'threat'),
  ('going to rape you', 'word', 'block', 'threat'),
  ('gonna rape you', 'word', 'block', 'threat'),
  ('i will leak your nudes', 'word', 'block', 'threat'),
  ('i go leak your nudes', 'word', 'block', 'threat'),
  ('leak your nudes', 'word', 'block', 'threat'),
  ('pay me or i leak', 'word', 'block', 'threat'),
  ('send money or i post your', 'word', 'block', 'threat'),
  ('hang yourself', 'word', 'block', 'abuse'),
  ('go hang yourself', 'word', 'block', 'abuse'),
  ('kill urself', 'word', 'block', 'abuse'),
  ('hope you die', 'word', 'flag', 'abuse'),
  ('i hope you die', 'word', 'flag', 'abuse'),
  ('i hope you die soon', 'word', 'flag', 'abuse'),
  ('go and die', 'word', 'flag', 'abuse'),
  ('go die', 'word', 'flag', 'abuse'),
  ('you should die', 'word', 'flag', 'abuse'),
  ('you deserve to die', 'word', 'flag', 'abuse'),
  ('die slowly', 'word', 'flag', 'abuse'),
  ('drink bleach', 'word', 'flag', 'abuse'),
  ('cunt', 'word', 'flag', 'abuse'),
  ('cunts', 'word', 'flag', 'abuse'),
  ('whore', 'word', 'flag', 'abuse'),
  ('whores', 'word', 'flag', 'abuse'),
  ('slut', 'word', 'flag', 'abuse'),
  ('sluts', 'word', 'flag', 'abuse'),
  ('motherfucker', 'word', 'flag', 'abuse'),
  ('mother fucker', 'word', 'flag', 'abuse'),
  ('fuck you', 'word', 'flag', 'abuse'),
  ('fuck off', 'word', 'flag', 'abuse'),
  ('fuck your mother', 'word', 'flag', 'abuse'),
  ('fuck your mama', 'word', 'flag', 'abuse'),
  ('suck my dick', 'word', 'flag', 'abuse'),
  ('ashawo', 'word', 'flag', 'abuse'),
  ('ashewo', 'word', 'flag', 'abuse'),
  ('olosho', 'word', 'flag', 'abuse'),
  ('oloshi', 'word', 'flag', 'abuse'),
  ('agbaya', 'word', 'flag', 'abuse'),
  ('kill all igbos', 'word', 'block', 'hate'),
  ('kill all igbo', 'word', 'block', 'hate'),
  ('kill all hausas', 'word', 'block', 'hate'),
  ('kill all hausa', 'word', 'block', 'hate'),
  ('kill all yorubas', 'word', 'block', 'hate'),
  ('kill all yoruba', 'word', 'block', 'hate'),
  ('kill all fulani', 'word', 'block', 'hate'),
  ('kill all fulanis', 'word', 'block', 'hate'),
  ('kill all muslims', 'word', 'block', 'hate'),
  ('kill all christians', 'word', 'block', 'hate'),
  ('kill all jews', 'word', 'block', 'hate'),
  ('kill all gays', 'word', 'block', 'hate'),
  ('kill all northerners', 'word', 'block', 'hate'),
  ('kill all southerners', 'word', 'block', 'hate'),
  ('exterminate the igbos', 'word', 'block', 'hate'),
  ('exterminate igbos', 'word', 'block', 'hate'),
  ('wipe out the igbos', 'word', 'block', 'hate'),
  ('wipe out igbos', 'word', 'block', 'hate'),
  ('gas the jews', 'word', 'block', 'hate'),
  ('nigger', 'word', 'block', 'hate'),
  ('niggers', 'word', 'block', 'hate'),
  ('faggot', 'word', 'block', 'hate'),
  ('faggots', 'word', 'block', 'hate'),
  ('kaffir', 'word', 'block', 'hate'),
  ('kaffirs', 'word', 'block', 'hate'),
  ('wetback', 'word', 'block', 'hate'),
  ('wetbacks', 'word', 'block', 'hate'),
  ('raghead', 'word', 'block', 'hate'),
  ('ragheads', 'word', 'block', 'hate'),
  ('towelhead', 'word', 'block', 'hate'),
  ('towelheads', 'word', 'block', 'hate'),
  ('tranny', 'word', 'block', 'hate'),
  ('trannies', 'word', 'block', 'hate'),
  ('nigga', 'word', 'flag', 'hate'),
  ('niggas', 'word', 'flag', 'hate'),
  ('niggah', 'word', 'flag', 'hate'),
  ('fag', 'word', 'flag', 'hate'),
  ('fags', 'word', 'flag', 'hate'),
  ('dyke', 'word', 'flag', 'hate'),
  ('dykes', 'word', 'flag', 'hate'),
  ('shemale', 'word', 'flag', 'hate'),
  ('chink', 'word', 'flag', 'hate'),
  ('chinks', 'word', 'flag', 'hate'),
  ('gook', 'word', 'flag', 'hate'),
  ('gooks', 'word', 'flag', 'hate'),
  ('spic', 'word', 'flag', 'hate'),
  ('spics', 'word', 'flag', 'hate'),
  ('coon', 'word', 'flag', 'hate'),
  ('coons', 'word', 'flag', 'hate'),
  ('paki', 'word', 'flag', 'hate'),
  ('beaner', 'word', 'flag', 'hate'),
  ('beaners', 'word', 'flag', 'hate'),
  ('retard', 'word', 'flag', 'hate'),
  ('retarded', 'word', 'flag', 'hate'),
  ('retards', 'word', 'flag', 'hate'),
  ('spastic', 'word', 'flag', 'hate'),
  ('mongoloid', 'word', 'flag', 'hate'),
  ('go back to africa', 'word', 'flag', 'hate'),
  ('go back to your country', 'word', 'flag', 'hate'),
  ('ethnic cleansing', 'word', 'flag', 'hate'),
  ('inyamiri', 'word', 'flag', 'hate'),
  ('nyamiri', 'word', 'flag', 'hate'),
  ('akata', 'word', 'flag', 'hate'),
  ('send nudes', 'word', 'flag', 'sexual'),
  ('nude pics for sale', 'word', 'flag', 'sexual'),
  ('nudes for sale', 'word', 'flag', 'sexual'),
  ('buy my nudes', 'word', 'flag', 'sexual'),
  ('sell nudes', 'word', 'flag', 'sexual'),
  ('dm for nudes', 'word', 'flag', 'sexual'),
  ('nude video call', 'word', 'flag', 'sexual'),
  ('sex for sale', 'word', 'flag', 'sexual'),
  ('dm for sex', 'word', 'flag', 'sexual'),
  ('come for sex', 'word', 'flag', 'sexual'),
  ('escort service', 'word', 'flag', 'sexual'),
  ('escorts available', 'word', 'flag', 'sexual'),
  ('hookup available', 'word', 'flag', 'sexual'),
  ('sex chat', 'word', 'flag', 'sexual'),
  ('video sex', 'word', 'flag', 'sexual'),
  ('sex for money', 'word', 'flag', 'sexual'),
  ('pay for sex', 'word', 'flag', 'sexual'),
  ('sugar daddy', 'word', 'flag', 'sexual'),
  ('sugar mummy', 'word', 'flag', 'sexual'),
  ('sugar mommy', 'word', 'flag', 'sexual'),
  ('need a sugar daddy', 'word', 'flag', 'sexual'),
  ('looking for sugar daddy', 'word', 'flag', 'sexual'),
  ('free porn', 'word', 'flag', 'sexual'),
  ('porn video', 'word', 'flag', 'sexual'),
  ('xxx video', 'word', 'flag', 'sexual'),
  ('xxx videos', 'word', 'flag', 'sexual'),
  ('nude videos', 'word', 'flag', 'sexual'),
  ('leaked nudes', 'word', 'flag', 'sexual'),
  ('sex tape', 'word', 'flag', 'sexual'),
  ('i want to die', 'word', 'support', 'self_harm'),
  ('i wanna die', 'word', 'support', 'self_harm'),
  ('kill myself', 'word', 'support', 'self_harm'),
  ('killing myself', 'word', 'support', 'self_harm'),
  ('end my life', 'word', 'support', 'self_harm'),
  ('ending my life', 'word', 'support', 'self_harm'),
  ('take my own life', 'word', 'support', 'self_harm'),
  ('end it all', 'word', 'support', 'self_harm'),
  ('i dont want to live', 'word', 'support', 'self_harm'),
  ('i don''t want to live', 'word', 'support', 'self_harm'),
  ('dont want to be alive', 'word', 'support', 'self_harm'),
  ('no reason to live', 'word', 'support', 'self_harm'),
  ('better off dead', 'word', 'support', 'self_harm'),
  ('i wish i was dead', 'word', 'support', 'self_harm'),
  ('i wish i were dead', 'word', 'support', 'self_harm'),
  ('i want to end it', 'word', 'support', 'self_harm'),
  ('suicidal', 'word', 'support', 'self_harm'),
  ('commit suicide', 'word', 'support', 'self_harm'),
  ('i wan die', 'word', 'support', 'self_harm'),
  ('i no wan live', 'word', 'support', 'self_harm'),
  ('i wan kill myself', 'word', 'support', 'self_harm'),
  ('i go kill myself', 'word', 'support', 'self_harm'),
  ('make i just die', 'word', 'support', 'self_harm')
ON CONFLICT (lower(term)) DO NOTHING;
